### ISSUE TITLE
Kibana fails with an “hapi-auth-cookie already registered” error

### ISSUE THREAD

**Issue by bgandon** [cloudfoundry-community/logsearch-for-cloudfoundry#326]
Hi guys,

Hope you are doing great!

Whenever I deploy a brand new Logsearch `v210.2.0`, or I upgrade from Logsearch `v209.1.0` to `v210.2.0`, I always hit a `Plugin hapi-auth-cookie already registered` error.

Initial set of versions:
```yaml
logsearch_version: "209.1.0"
logsearch_for_cloudfoundry_version: "207.0.3"
```

Upgraded versions:
```yaml
logsearch_version: "210.2.0"
logsearch_for_cloudfoundry_version: "210.2.0"
```

Stack trace found in `/var/vcap/sys/log/kibana/kibana.stderr.log`:
```
FATAL Error: Plugin hapi-auth-cookie already registered in: http://0.0.0.0:5601
    at Object.exports.assert (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hoek/lib/index.js:740:11)
    at each (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/plugin.js:287:26)
    at iterate (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/items/lib/index.js:36:13)
    at done (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/items/lib/index.js:28:25)
    at Object.exports.register (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/plugins/authentication/node_modules/bell/lib/index.js:26:5)
    at Object.target [as register] (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Plugin.internals.Plugin.register (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/plugin.js:320:11)
    at Plugin.init [as externalInit] (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/plugins/authentication/index.js:138:14)
    at asyncRegister (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/src/server/plugins/lib/plugin.js:72:20)
    at Object.register (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/src/server/plugins/lib/plugin.js:77:7)
    at Object.target [as register] (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Server.internals.Plugin.register (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/plugin.js:320:11)
    at Promise (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/promises.js:24:16)
    at new Promise (<anonymous>)
    at Object.exports.wrap (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/promises.js:13:12)
    at module.exports.internals.Server.internals.Plugin.register (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/hapi/lib/plugin.js:164:25)
    at Plugin.init (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/src/server/plugins/lib/plugin.js:82:28)
    at Plugin.init (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/node_modules/lodash/index.js:7407:25)
    at callPluginHook (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/src/server/plugins/lib/call_plugin_hook.js:37:25)
    at callHookOnPlugins (/var/vcap/data/packages/kibana/ad4ad79a1caf03b08be797d2aa42d3e7b3a1e250/src/server/plugins/initialize_mixin.js:28:37)
    at <anonymous>
```

I'm deploying a pretty standard Logsearch deployment, as detailed in this [Logseach GBE subsystem spec](https://github.com/gstackio/gstack-bosh-environment/blob/master/deployments/logsearch/conf/spec.yml) file. And the related custom ops files are defined in [this `features` directory](https://github.com/gstackio/gstack-bosh-environment/tree/master/deployments/logsearch/features). (GBE is a framework for deploying many BOSH deployments that are integrated together.)

Do you have any idea of what can be wrong in my setup?

Please note that I've only guessed this `hapi-auth-cookie` issue would be more related to “logsearch-for-cloudfoundry” than the “logsearch-boshrelease”. If it's not the case, don't hesitate to tell me and I'll move this issue to the proper project.

Thank you for your support!

Best,
Benjamin

**Comment by axelaris** [comment]
Hi @bgandon,
this issue should be fixed in v210.3.0
Could you please check and confirm?
